
(function(){
  if(typeof adjustState==='undefined'||!window.__V142Api)return;
  const api=window.__V142Api,IDS=ADJUST_BRUSH_DEFS.map(x=>x.id),PRESET_KEY='ai_adjust_v144_combo_presets';
  const DIRS={up:'上方',upRight:'右上方',right:'右侧',downRight:'右下方',down:'下方',downLeft:'左下方',left:'左侧',upLeft:'左上方'};
  const SUBJECT_TYPES={product:'产品',person:'人物',pet:'宠物',secondProduct:'第二产品',prop:'道具',custom:'自定义主体'};
  const REMOVE_IDS=new Set(['v142-red-remove','v142-prop-remove','v142-purple-remove']);
  const PARAM_ACTIONS=new Set(['scaleDown','scaleUp','move','angle','soften']);
  const STATIC_CLAUSES={
    'v142-red-remove':'删除文字、水印或字符，并根据周围纹理自然补全删除区域','v142-red-clear':'提升文字清晰度、笔画完整度和边缘锐度，修复模糊、重影或轻微变形','v142-product-material':'提升产品清晰度、玻璃或金属材质、边缘和光影细节','v142-person-detail':'提升人物面部、皮肤、头发、手部和轮廓清晰度，修复轻微变形','v142-person-pose':'轻微优化人物姿态与肢体自然度，不改变动作含义','v142-pet-detail':'提升宠物毛发层次、眼睛、鼻口和轮廓清晰度','v142-pet-pose':'轻微优化宠物姿态与四肢自然度，禁止增加肢体','v142-second-material':'统一第二产品与主产品的材质、清晰度、色温、投影和光线方向','v142-second-relation':'优化第二产品与主产品的前后层级、间距和视觉呼应','v142-prop-remove':'删除道具或辅助物件，并根据周围场景自然补全删除区域','v142-prop-material':'提升道具清晰度、材质、边缘与光影细节','v142-custom-detail':'提升自定义主体的清晰度、边缘、材质和光影细节','v142-custom-preserve':'修复自定义主体的轻微变形、锯齿或透视问题，稳定主体造型','v142-blue-color':'将背景颜色调整为与整体画面协调的浅色','v142-blue-gradient':'将背景改为柔和自然的深浅渐变，避免明显色带','v142-blue-clean':'清理背景杂物、污点或多余元素，并自然补全背景','v142-blue-depth':'适度增强背景空间层次和景深，使主体更突出','v142-blue-light':'调整背景亮度与对比度，使光影更协调并突出主体','v142-purple-remove':'删除装饰、图标、光效、线条或边框，并自然补全背景','v142-purple-color':'调整装饰元素颜色，使其与整体画面及产品主色协调'
  };
  const escAttr=s=>esc(String(s==null?'':s)).replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  const scope=id=>api.scopeFor(id),params=id=>api.params(id);
  let dragState=null;
  function loadPresets(){try{const x=JSON.parse(localStorage.getItem(PRESET_KEY)||'[]');return Array.isArray(x)?x:[];}catch(e){return[];}}
  let presets=loadPresets();
  function savePresets(){try{localStorage.setItem(PRESET_KEY,JSON.stringify(presets));}catch(e){}}
  function templateAction(t){if(t&&t.action)return t.action;const id=t?.id||'';if(/-down$/.test(id))return'scaleDown';if(/-up$/.test(id))return'scaleUp';if(/-move$/.test(id))return'move';if(/-angle$/.test(id))return'angle';if(/-soften$/.test(id))return'soften';return'custom';}
  function allTemplates(id){return api.sortedTemplates(scope(id));}
  function resolveTemplate(id,tid){return api.allTemplates(scope(id)).find(t=>t.id===tid)||api.findTemplate(tid)||null;}
  function validIds(id){return new Set(api.allTemplates(scope(id)).map(t=>t.id));}
  function ensure144(){
    api.ensureV142();adjustState.v143SelectedTemplates=adjustState.v143SelectedTemplates||{};adjustState.v144RecommendationSets=adjustState.v144RecommendationSets||{};adjustState.v144LibraryUi=adjustState.v144LibraryUi||{};adjustState.v144MoreOpen=adjustState.v144MoreOpen||{};
    IDS.forEach(id=>{const valid=validIds(id);let list=Array.isArray(adjustState.v143SelectedTemplates[id])?adjustState.v143SelectedTemplates[id].slice():[];list=[...new Set(list.filter(x=>valid.has(x)))];const current=adjustState.brushes[id]?.template||'';if(!list.length&&current&&valid.has(current))list=[current];adjustState.v143SelectedTemplates[id]=list;if(adjustState.brushes[id])adjustState.brushes[id].template=list[list.length-1]||'';adjustState.v144LibraryUi[id]=Object.assign({query:'',filter:'all'},adjustState.v144LibraryUi[id]||{});});
  }
  function selectedIds(id){ensure144();return adjustState.v143SelectedTemplates[id]||[];}
  function selectedTemplates(id){return selectedIds(id).map(tid=>resolveTemplate(id,tid)).filter(Boolean);}
  function noun(id){if(id==='red')return'文字';if(id==='blue')return'背景';if(id==='purple')return'装饰元素';return api.subjectNoun(id);}
  function displayLabel(id,t){return api.displayLabel(id,t);}
  function operationClause(id,t){const p=params(id),n=noun(id),a=templateAction(t);if(a==='scaleDown'){const v=Math.max(1,Math.min(80,Number(p.scalePct)||20));return`将${n}整体缩小 ${v}%（调整为原大小的 ${100-v}%）`;}if(a==='scaleUp'){const v=Math.max(1,Math.min(80,Number(p.scalePct)||20));return`将${n}整体放大 ${v}%（调整为原大小的 ${100+v}%）`;}if(a==='move'){const v=Math.max(1,Math.min(50,Number(p.movePct)||5)),d=DIRS[p.direction]||'右侧';return`将${n}从当前位置向${d}移动约 ${v}%`;}if(a==='angle'){const v=Math.max(1,Math.min(45,Number(p.angleDeg)||10));return`轻微调整${n}角度约 ${v}°，保持透视与落地关系自然`;}if(a==='soften'){const v=Math.max(5,Math.min(80,Number(p.effectPct)||25));return`将装饰效果弱化约 ${v}%，适度降低透明度、亮度或光效强度`;}if(STATIC_CLAUSES[t.id]){let c=STATIC_CLAUSES[t.id];if(t.id.startsWith('v142-custom-'))c=c.replace('自定义主体',n);return c;}const raw=typeof t.text==='function'?String(t.text(id)||''):String(t.text||'');return raw.trim()?`执行自定义要求：${raw.trim()}`:`应用“${t.label||'自定义模板'}”要求`;}
  function preserveClause(id,ts){const actions=new Set(ts.map(templateAction)),ids=new Set(ts.map(t=>t.id));if(id==='red'){if([...ids].some(x=>REMOVE_IDS.has(x)))return'自然补全删除区域；保持产品、人物、背景、装饰及未标注区域不变。';return'除上述已选操作外，保持文字内容、字体风格、颜色、字距、行距、对齐方式和层级关系不变；不要改变主体、背景、装饰和未标注区域。';}if(id==='blue')return'保持主体、文字、装饰、整体构图及未标注区域不变，避免污染主体边缘。';if(id==='purple'){const keep=['装饰造型','大小','位置','颜色','透明度','角度','层级'];const remove=k=>{const i=keep.indexOf(k);if(i>=0)keep.splice(i,1);};if(actions.has('scaleDown')||actions.has('scaleUp'))remove('大小');if(actions.has('move'))remove('位置');if(actions.has('soften'))remove('透明度');if(ids.has('v142-purple-color'))remove('颜色');if([...ids].some(x=>REMOVE_IDS.has(x)))return'自然补全删除区域；保持主体、文字、背景及未标注区域不变。';return`除上述已选操作外，保持${keep.join('、')}不变；不要改变主体、文字、背景和未标注区域。`;}const keep=['身份特征与主体造型','包装文字或关键细节','颜色','比例','大小','位置','角度','材质与光影','姿态'];const remove=k=>{const i=keep.indexOf(k);if(i>=0)keep.splice(i,1);};if(actions.has('scaleDown')||actions.has('scaleUp'))remove('大小');if(actions.has('move'))remove('位置');if(actions.has('angle'))remove('角度');if([...ids].some(x=>/material|detail|preserve/.test(x)))remove('材质与光影');if([...ids].some(x=>/pose|relation/.test(x)))remove('姿态');if([...ids].some(x=>REMOVE_IDS.has(x)))return'自然补全删除区域；保持主产品、人物、文字、背景、装饰和未标注区域不变。';return`除上述已选操作外，保持${keep.join('、')}不变；不要新增、删除或改写其他区域。`;}
  function composePrompt(id){const ts=selectedTemplates(id);if(!ts.length)return'';const clauses=ts.map(t=>operationClause(id,t)),actions=new Set(ts.map(templateAction));const prefix=clauses.length===1?`请只编辑标注区域内的${noun(id)}，完成以下操作：`:`请只编辑标注区域内的${noun(id)}，在同一次编辑中按当前顺序完成以下 ${clauses.length} 项操作：`;const body=clauses.map((c,i)=>`${i+1}. ${c}`).join('；');const joint=(actions.has('move')&&(actions.has('scaleDown')||actions.has('scaleUp')))?'缩放与移动必须作为同一主体的一次联合变换完成，不要分别重绘；移动后自然补全原位置及新暴露的背景。 ':actions.has('move')?'移动后自然补全原位置及新暴露的背景。 ':'';return`${prefix}${body}。${joint}${preserveClause(id,ts)}`;}
  function syncPrompt(id,historyLabel){ensure144();const list=adjustState.v143SelectedTemplates[id]||[],prompt=composePrompt(id);adjustState.brushes[id].template=list[list.length-1]||'';adjustState.brushes[id].prompt=prompt;const ta=document.querySelector(`[data-adj-brush-prompt="${id}"]`);if(ta)ta.value=prompt;adjustRefreshBrushSummary&&adjustRefreshBrushSummary();adjustScheduleAutosave&&adjustScheduleAutosave();if(historyLabel)adjustPushHistory(historyLabel);}
  function toggleTemplate(id,tid){ensure144();const t=resolveTemplate(id,tid);if(!t)return;let list=selectedIds(id).slice(),idx=list.indexOf(tid);if(idx>=0)list.splice(idx,1);else{const action=templateAction(t),isRemove=REMOVE_IDS.has(tid);if(isRemove)list=[];else list=list.filter(x=>!REMOVE_IDS.has(x));if(action==='scaleDown'||action==='scaleUp')list=list.filter(x=>{const a=templateAction(resolveTemplate(id,x));return a!=='scaleDown'&&a!=='scaleUp';});list.push(tid);api.prefs.usage[tid]=Number(api.prefs.usage[tid]||0)+1;api.savePrefs();}adjustState.v143SelectedTemplates[id]=list;syncPrompt(id,'更新 V14.4 多选模板组合');renderAdjustView();}
  function clearTemplates(id){adjustState.v143SelectedTemplates[id]=[];adjustState.brushes[id].template='';adjustState.brushes[id].prompt='';adjustPushHistory('清空 V14.4 模板组合');adjustScheduleAutosave&&adjustScheduleAutosave();renderAdjustView();}
  function recommendationIds(id){ensure144();const sc=scope(id),valid=validIds(id);let item=adjustState.v144RecommendationSets[id];if(!item||item.scope!==sc||!Array.isArray(item.ids)||item.ids.some(x=>!valid.has(x))){item={scope:sc,ids:api.sortedTemplates(sc).slice(0,5).map(t=>t.id)};adjustState.v144RecommendationSets[id]=item;}return item.ids.slice(0,5);}
  function cardHtml(id,d,t){const list=selectedIds(id),order=list.indexOf(t.id)+1,on=order>0,fav=!!api.prefs.favorites[t.id],u=Number(api.prefs.usage[t.id]||0);return`<div class="v144-template-card ${on?'on':''}" style="--region-color:${d.color}"><button type="button" class="v144-template-use" data-v144-template-toggle="${escAttr(t.id)}" data-brush-id="${id}"><span class="v144-template-check" data-order="${on?order:''}"></span><b>${esc(displayLabel(id,t))}</b><small>${on?`已选 · 第 ${order} 项`:fav?'已收藏':u?`使用 ${u} 次`:'点击加入组合'}</small></button><button type="button" class="v144-template-fav ${fav?'on':''}" data-v144-favorite="${escAttr(t.id)}" title="${fav?'取消收藏':'收藏模板'}">${fav?'★':'☆'}</button></div>`;}
  function comboSummary(id){const ts=selectedTemplates(id);if(!ts.length)return`<div class="v144-combo-summary"><div class="v144-combo-head"><b>尚未选择模板</b><span>可同时选择“缩小 + 移动”等组合</span></div></div>`;return`<div class="v144-combo-summary"><div class="v144-combo-head"><b>已选择 ${ts.length} 项 <span class="v144-multi-badge">可拖拽排序</span></b><button type="button" class="v144-clear" data-v144-clear="${id}">清空组合</button></div><div class="v144-combo-order">${ts.map((t,i)=>`<div class="v144-order-chip" draggable="true" data-v144-sort-item="${escAttr(t.id)}" data-brush-id="${id}"><i>${i+1}</i><span>${esc(displayLabel(id,t))}</span><em>⋮⋮</em></div>`).join('')}</div></div>`;}
  function parameterHtml(id,ts){const p=params(id),acts=new Set(ts.map(templateAction)),hasScale=acts.has('scaleDown')||acts.has('scaleUp'),hasMove=acts.has('move'),hasAngle=acts.has('angle'),hasSoften=acts.has('soften');if(!hasScale&&!hasMove&&!hasAngle&&!hasSoften)return'';return`<div class="v144-param-box"><div class="v144-param-title"><b>当前组合参数</b><span>只显示已选模板需要的控件</span></div>${hasScale?`<label class="v142-slider"><span>缩放幅度</span><input type="range" min="5" max="50" step="1" value="${p.scalePct}" data-v144-scale="${id}"><output>${p.scalePct}%</output></label>`:''}${hasMove?`<label class="v142-slider"><span>移动距离</span><input type="range" min="1" max="30" step="1" value="${p.movePct}" data-v144-move="${id}"><output>${p.movePct}%</output></label><div class="v144-direction-title"><b>移动方向</b><span>仅保留方向与距离</span></div><div class="v142-direction-grid">${Object.entries(DIRS).map(([k,v])=>`<button type="button" class="${p.direction===k?'on':''}" data-v144-direction="${k}" data-brush-id="${id}">${esc(v)}</button>`).join('')}</div>`:''}${hasAngle?`<label class="v142-slider"><span>角度幅度</span><input type="range" min="1" max="30" step="1" value="${p.angleDeg}" data-v144-angle="${id}"><output>${p.angleDeg}°</output></label>`:''}${hasSoften?`<label class="v142-slider"><span>弱化幅度</span><input type="range" min="5" max="60" step="1" value="${p.effectPct}" data-v144-effect="${id}"><output>${p.effectPct}%</output></label>`:''}</div>`;}
  function presetSummary(id,p){return p.templateIds.map(tid=>resolveTemplate(id,tid)).filter(Boolean).map(t=>displayLabel(id,t)).join(' + ');}
  function presetsHtml(id){const list=presets.filter(p=>p.scope===scope(id)).sort((a,b)=>(b.useCount||0)-(a.useCount||0)||String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));return`<div class="v144-section"><div class="v144-section-head"><b>完整组合预设</b><span>保存模板顺序、百分比、方向与主体类型</span></div><div class="v144-preset-create"><input type="text" data-v144-preset-name="${id}" placeholder="预设名称，例如：缩小并右移"><button type="button" class="btn btn-ghost" data-v144-preset-save="${id}">保存当前组合</button></div><div class="v144-preset-list">${list.length?list.map(p=>`<div class="v144-preset-item"><div><b>${esc(p.name)}</b><small>${esc(presetSummary(id,p)||'模板已失效')} · 使用 ${Number(p.useCount||0)} 次</small></div><button type="button" class="mini-btn" data-v144-preset-apply="${escAttr(p.id)}" data-brush-id="${id}">一键应用</button><button type="button" class="mini-btn v144-preset-delete" data-v144-preset-delete="${escAttr(p.id)}">删除</button></div>`).join(''):`<div class="v144-preset-empty">当前区域类型还没有组合预设。</div>`}</div></div>`;}
  function templateMeta(t){const custom=api.prefs.custom.some(x=>x.id===t.id),fav=!!api.prefs.favorites[t.id],action=templateAction(t);return{custom,fav,param:PARAM_ACTIONS.has(action),label:custom?'自定义模板':PARAM_ACTIONS.has(action)?'参数模板':'效果模板'};}
  function libraryResultsHtml(id){const ui=adjustState.v144LibraryUi[id]||{query:'',filter:'all'},q=String(ui.query||'').trim().toLowerCase(),selected=new Set(selectedIds(id));let list=allTemplates(id).filter(t=>{const m=templateMeta(t);if(ui.filter==='favorite'&&!m.fav)return false;if(ui.filter==='custom'&&!m.custom)return false;if(ui.filter==='param'&&!m.param)return false;if(ui.filter==='effect'&&(m.custom||m.param))return false;const hay=(t.label+' '+t.id+' '+m.label).toLowerCase();return!q||hay.includes(q);});if(!list.length)return`<div class="v144-library-empty">没有符合当前搜索和分类的模板。</div>`;return list.map(t=>{const m=templateMeta(t),on=selected.has(t.id),u=Number(api.prefs.usage[t.id]||0);return`<div class="v144-library-item ${on?'on':''}"><div><b>${esc(displayLabel(id,t))}</b><small>${m.label}${m.fav?' · 已收藏':''}${u?` · 使用 ${u} 次`:''}</small></div><button type="button" class="v144-library-star ${m.fav?'on':''}" data-v144-library-fav="${escAttr(t.id)}" title="${m.fav?'取消收藏':'收藏'}">${m.fav?'★':'☆'}</button><button type="button" class="mini-btn" data-v144-library-toggle="${escAttr(t.id)}" data-brush-id="${id}">${on?'移除':'加入'}</button>${m.custom?`<button type="button" class="mini-btn v144-library-delete" data-v144-custom-delete="${escAttr(t.id)}">删除</button>`:'<span></span>'}</div>`;}).join('');}
  function libraryHtml(id){const ui=adjustState.v144LibraryUi[id]||{query:'',filter:'all'};return`<div class="v144-section"><div class="v144-section-head"><b>统一模板选择器</b><button type="button" class="mini-btn" data-v144-custom-new="${id}">+ 自定义模板</button></div><div class="v144-library-controls"><input type="search" value="${escAttr(ui.query||'')}" data-v144-template-search="${id}" placeholder="搜索模板名称"><select data-v144-template-filter="${id}"><option value="all" ${ui.filter==='all'?'selected':''}>全部模板</option><option value="favorite" ${ui.filter==='favorite'?'selected':''}>收藏模板</option><option value="custom" ${ui.filter==='custom'?'selected':''}>自定义模板</option><option value="param" ${ui.filter==='param'?'selected':''}>参数模板</option><option value="effect" ${ui.filter==='effect'?'selected':''}>效果模板</option></select></div><div class="v144-library-results" data-v144-library-results="${id}">${libraryResultsHtml(id)}</div></div>`;}
  function savePreset(id){ensure144();const ids=selectedIds(id).slice();if(!ids.length){setActionStatus('error','请先选择至少一个模板，再保存组合预设',false);return;}const input=document.querySelector(`[data-v144-preset-name="${id}"]`),auto=selectedTemplates(id).map(t=>t.label).join(' + '),name=String(input?.value||'').trim()||auto||'未命名组合';const sc=scope(id),now=new Date().toISOString(),data={id:'v144-preset-'+Date.now().toString(36),name,scope:sc,templateIds:ids,params:JSON.parse(JSON.stringify(params(id))),subjectType:(id==='amber'||id==='green')?(adjustState.v142SubjectTypes[id]||null):null,customSubject:(id==='amber'||id==='green')?(adjustState.v142CustomSubjectNames[id]||''):null,createdAt:now,updatedAt:now,useCount:0};const old=presets.find(p=>p.scope===sc&&p.name===name);if(old)Object.assign(old,data,{id:old.id,createdAt:old.createdAt||now,useCount:old.useCount||0});else presets.push(data);savePresets();setActionStatus('success',`组合预设“${name}”已保存`,false);renderAdjustView();}
  function applyPreset(id,pid){const p=presets.find(x=>x.id===pid);if(!p)return;if((id==='amber'||id==='green')&&p.subjectType){adjustState.v142SubjectTypes[id]=p.subjectType;if(p.customSubject)adjustState.v142CustomSubjectNames[id]=p.customSubject;api.updateLayerNames();adjustState.v144RecommendationSets[id]=null;}const valid=validIds(id);adjustState.v143SelectedTemplates[id]=p.templateIds.filter(x=>valid.has(x));adjustState.v142TemplateParams[id]=Object.assign({},params(id),p.params||{});p.useCount=Number(p.useCount||0)+1;p.updatedAt=new Date().toISOString();savePresets();syncPrompt(id,'应用 V14.4 完整组合预设');setActionStatus('success',`已应用组合预设“${p.name}”`,false);renderAdjustView();}
  function deletePreset(pid){const p=presets.find(x=>x.id===pid);presets=presets.filter(x=>x.id!==pid);savePresets();setActionStatus('success',p?`组合预设“${p.name}”已删除`:'组合预设已删除',false);renderAdjustView();}
  function openCustomModal(id){modalOpen(`<h3>新建自定义模板</h3><p class="hint">新模板会进入当前区域类型的统一模板选择器，并自动加入当前组合。</p><div class="v144-custom-form"><label>模板名称</label><input id="v144-custom-label" type="text" placeholder="例如：主体左移并提升材质"><label>完整修改指令</label><textarea id="v144-custom-text" placeholder="输入可直接用于当前区域的完整修改指令"></textarea></div><div class="row" style="margin-top:12px"><button class="btn btn-violet" data-v144-custom-save="${id}">保存并加入组合</button><button class="btn btn-ghost" data-mclose>取消</button></div>`,true);}
  function saveCustom(id){const label=document.getElementById('v144-custom-label')?.value.trim(),text=document.getElementById('v144-custom-text')?.value.trim();if(!label||!text){setActionStatus('error','请填写模板名称和完整指令',false);return;}const tid='v144-custom-'+Date.now().toString(36);api.prefs.custom.push({id:tid,label,text,scope:scope(id),createdAt:new Date().toISOString()});api.prefs.favorites[tid]=true;api.savePrefs();api.registerTemplates();modalClose();toggleTemplate(id,tid);setActionStatus('success','自定义模板已保存并加入当前组合',false);}
  function deleteCustom(tid){api.prefs.custom=api.prefs.custom.filter(x=>x.id!==tid);delete api.prefs.favorites[tid];delete api.prefs.usage[tid];IDS.forEach(id=>{adjustState.v143SelectedTemplates[id]=(adjustState.v143SelectedTemplates[id]||[]).filter(x=>x!==tid);const rec=adjustState.v144RecommendationSets[id];if(rec&&Array.isArray(rec.ids))rec.ids=rec.ids.filter(x=>x!==tid);});presets.forEach(p=>{p.templateIds=(p.templateIds||[]).filter(x=>x!==tid);});api.savePrefs();savePresets();const id=adjustState.activeBrush||'red';syncPrompt(id,'删除自定义模板');setActionStatus('success','自定义模板已删除',false);renderAdjustView();}
  function editorPanel(){ensure144();const id=adjustState.activeBrush||'red',d=ADJUST_BRUSH_DEFS.find(x=>x.id===id)||ADJUST_BRUSH_DEFS[0],info=api.regionInfo(id),state=adjustState.brushes[id],selected=selectedTemplates(id),cards=recommendationIds(id).map(tid=>resolveTemplate(id,tid)).filter(Boolean).map(t=>cardHtml(id,d,t)).join(''),ready=!!(adjustState.img&&adjustColorStrokeCount(id)>0&&String(state.prompt||'').trim()&&!adjustState.aiBusy),type=id==='amber'||id==='green'?(SUBJECT_TYPES[adjustState.v142SubjectTypes?.[id]]||'主体'):info.kind,paramBlock=parameterHtml(id,selected);return`<div class="v14-panel-head"><div><h3>当前区域指令</h3><p>推荐模板稳定多选；已选组合支持拖拽排序与预设复用</p></div><span class="v14-status-pill ${ready?'ok':'warn'}">${ready?'可生成':'待完善'}</span></div><div class="v14-panel-body"><div class="v142-region-context" style="--region-color:${d.color}"><div class="v142-region-main"><i></i><div><b>${esc(info.name)} · ${esc(info.kind)}</b><small>${adjustColorStrokeCount(id)} 笔标注；当前类型：${esc(type)}</small></div></div>${api.subjectSelector(id)}</div><textarea class="v14-prompt" data-adj-brush-prompt="${id}" placeholder="${escAttr(info.placeholder)}">${esc(state.prompt||'')}</textarea><div class="v142-rec-head"><b>推荐模板（可多选）</b><span>再次点击取消；选择其他模板不会顶替已有选择</span></div><div class="v144-template-grid">${cards}</div>${comboSummary(id)}<div class="v144-combo-note" style="--region-color:${d.color}">拖动已选模板可调整执行顺序，提示词会实时同步。例如可将“提升材质 → 缩小 → 移动”改为“缩小 → 移动 → 提升材质”。</div><button type="button" class="btn btn-violet v142-generate" data-v142-generate="${id}" ${ready?'':'disabled'}>${adjustState.aiBusy?'正在处理…':'单独生成'}</button><details class="v142-more" data-v144-more="${id}" ${adjustState.v144MoreOpen[id]?'open':''}><summary><b>更多设置</b><span>${paramBlock?'组合参数 · ':''}组合预设 · 模板选择器 · Mask</span></summary><div class="v142-more-body">${paramBlock}${presetsHtml(id)}${libraryHtml(id)}<div class="v142-run-settings"><label>候选数量<select data-adj-candidate-count><option value="2" ${adjustState.candidateCount===2?'selected':''}>2 个</option><option value="3" ${adjustState.candidateCount===3?'selected':''}>3 个</option><option value="4" ${adjustState.candidateCount===4?'selected':''}>4 个</option></select></label><label>联合执行范围<select data-adj-ai-scope><option value="active" ${adjustState.aiScope==='active'?'selected':''}>当前区域</option><option value="all" ${adjustState.aiScope==='all'?'selected':''}>全部有效区域</option></select></label></div><div class="v142-more-actions"><button type="button" class="btn btn-ghost" data-adj-mask="${id}" ${adjustColorStrokeCount(id)?'':'disabled'}>导出当前 Mask</button><button type="button" class="btn btn-ghost" data-v142-conflict-check="${id}">立即检查冲突</button></div>${api.conflictStatusHtml()}</div></details></div>`;}
  function applyEditor(){ensure144();const panels=[...document.querySelectorAll('.v14-right .v14-panel')],current=panels.find(p=>p.querySelector('.v14-panel-head h3')?.textContent.trim()==='当前区域指令');if(current)current.innerHTML=editorPanel();}
  function refreshLibrary(id){const box=document.querySelector(`[data-v144-library-results="${id}"]`);if(box)box.innerHTML=libraryResultsHtml(id);}
  function reorder(id,sourceTid,targetTid,after){let list=selectedIds(id).slice(),from=list.indexOf(sourceTid),to=list.indexOf(targetTid);if(from<0||to<0||from===to)return;list.splice(from,1);to=list.indexOf(targetTid)+(after?1:0);list.splice(to,0,sourceTid);adjustState.v143SelectedTemplates[id]=list;syncPrompt(id,'拖拽调整模板组合顺序');renderAdjustView();}

  const baseWorkspace=adjustWorkspaceHtml;adjustWorkspaceHtml=function(){let html=baseWorkspace();html=html.replace(/图片微调 · V14\.4 专业工作台/g,'图片微调 · V14.4 专业工作台').replace(/图片微调 · V14\.3 专业工作台/g,'图片微调 · V14.4 专业工作台').replace(/图片微调 · V14\.2 专业工作台/g,'图片微调 · V14.4 专业工作台');html=html.replace('删除目标位置九宫格；推荐模板支持多选，并按选择顺序自动生成兼容的组合提示词。','修复推荐模板被顶替问题；新增拖拽排序、完整组合预设及统一搜索分类模板选择器。');return html;};
  const baseRender=renderAdjustView;renderAdjustView=function(){ensure144();baseRender();applyEditor();};
  const basePayload=adjustProjectPayload;adjustProjectPayload=function(mode='full'){ensure144();const p=basePayload(mode);p.schema='ai_image_adjustment_project_v144';p.version='V14.4';p.state=p.state||{};p.state.v143SelectedTemplates=JSON.parse(JSON.stringify(adjustState.v143SelectedTemplates));p.state.v144RecommendationSets=JSON.parse(JSON.stringify(adjustState.v144RecommendationSets));p.state.v144CombinationMode='stable_multi_select_drag_presets';return p;};
  if(typeof adjustInstructionPayload==='function'){const baseInstruction=adjustInstructionPayload;adjustInstructionPayload=function(ids){ensure144();const p=baseInstruction(ids);p.version='V14.4';p.regionTemplateMode='stable_multi_select_drag_presets_v144';p.selectedTemplateCombinations={};(ids||[]).forEach(id=>{p.selectedTemplateCombinations[id]=selectedIds(id).slice();});p.constraints=p.constraints||[];p.constraints.push('同一区域已选模板必须严格按照拖拽后的顺序在一次编辑中联合执行');p.constraints.push('新增模板不得覆盖或替换其他已选模板，除非属于删除冲突或放大缩小互斥');return p;};}
  const baseImport=adjustImportProjectFile;adjustImportProjectFile=async function(file){let parsed=null;try{parsed=JSON.parse(await file.text());}catch(e){}await baseImport(file);if(parsed?.state?.v143SelectedTemplates)adjustState.v143SelectedTemplates=parsed.state.v143SelectedTemplates;if(parsed?.state?.v144RecommendationSets)adjustState.v144RecommendationSets=parsed.state.v144RecommendationSets;ensure144();renderAdjustView();};
  if(typeof adjustSnapshot==='function'){const baseSnapshot=adjustSnapshot;adjustSnapshot=function(label){ensure144();const x=baseSnapshot(label);x.v144={selectedTemplates:JSON.parse(JSON.stringify(adjustState.v143SelectedTemplates)),recommendations:JSON.parse(JSON.stringify(adjustState.v144RecommendationSets))};return x;};}
  if(typeof adjustRestoreSnapshot==='function'){const baseRestore=adjustRestoreSnapshot;adjustRestoreSnapshot=function(x){baseRestore(x);if(x?.v144?.selectedTemplates)adjustState.v143SelectedTemplates=x.v144.selectedTemplates;if(x?.v144?.recommendations)adjustState.v144RecommendationSets=x.v144.recommendations;ensure144();};}
  if(typeof adjustResetRuntime==='function'){const baseReset=adjustResetRuntime;adjustResetRuntime=function(){baseReset();adjustState.v143SelectedTemplates={};adjustState.v144RecommendationSets={};adjustState.v144LibraryUi={};ensure144();};}
  if(typeof adjustOpenProjectSave==='function'){const baseOpen=adjustOpenProjectSave;adjustOpenProjectSave=function(){baseOpen();setTimeout(()=>{document.querySelectorAll('.modal h3,.modal-card h3').forEach(h=>{if(/保存 V14(?:\.1|\.2|\.3|\.4)? 微调项目/.test(h.textContent||''))h.textContent='保存 V14.4 微调项目';});},0);};}
  if(typeof adjustExportProject==='function'){adjustExportProject=function(mode){if(!mode){adjustOpenProjectSave();return;}const payload=adjustProjectPayload(mode),blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a'),base=(adjustState.name||'image').replace(/\.[^.]+$/,'').replace(/[\\/:*?"<>|]+/g,'-');a.href=URL.createObjectURL(blob);a.download=`${base}-微调项目-v14.4-${mode==='light'?'轻量':'完整'}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500);setActionStatus('success',mode==='light'?'V14.4 轻量项目已保存':'V14.4 完整项目已保存',false);};}

  document.addEventListener('click',e=>{if(curView!=='adjust')return;const toggle=e.target.closest('[data-v144-template-toggle],[data-v144-library-toggle]');if(toggle){e.preventDefault();e.stopImmediatePropagation();toggleTemplate(toggle.dataset.brushId,toggle.dataset.v144TemplateToggle||toggle.dataset.v144LibraryToggle);return;}const fav=e.target.closest('[data-v144-favorite],[data-v144-library-fav]');if(fav){e.preventDefault();e.stopImmediatePropagation();const tid=fav.dataset.v144Favorite||fav.dataset.v144LibraryFav;api.prefs.favorites[tid]=!api.prefs.favorites[tid];if(!api.prefs.favorites[tid])delete api.prefs.favorites[tid];api.savePrefs();renderAdjustView();return;}const clear=e.target.closest('[data-v144-clear]');if(clear){e.preventDefault();e.stopImmediatePropagation();clearTemplates(clear.dataset.v144Clear);return;}const dir=e.target.closest('[data-v144-direction]');if(dir){e.preventDefault();e.stopImmediatePropagation();const id=dir.dataset.brushId;params(id).direction=dir.dataset.v144Direction;syncPrompt(id,'调整组合模板移动方向');renderAdjustView();return;}const ps=e.target.closest('[data-v144-preset-save]');if(ps){e.preventDefault();e.stopImmediatePropagation();savePreset(ps.dataset.v144PresetSave);return;}const pa=e.target.closest('[data-v144-preset-apply]');if(pa){e.preventDefault();e.stopImmediatePropagation();applyPreset(pa.dataset.brushId,pa.dataset.v144PresetApply);return;}const pd=e.target.closest('[data-v144-preset-delete]');if(pd){e.preventDefault();e.stopImmediatePropagation();deletePreset(pd.dataset.v144PresetDelete);return;}const cn=e.target.closest('[data-v144-custom-new]');if(cn){e.preventDefault();e.stopImmediatePropagation();openCustomModal(cn.dataset.v144CustomNew);return;}const cs=e.target.closest('[data-v144-custom-save]');if(cs){e.preventDefault();e.stopImmediatePropagation();saveCustom(cs.dataset.v144CustomSave);return;}const cd=e.target.closest('[data-v144-custom-delete]');if(cd){e.preventDefault();e.stopImmediatePropagation();deleteCustom(cd.dataset.v144CustomDelete);return;}},true);
  document.addEventListener('input',e=>{if(curView!=='adjust')return;const search=e.target.closest('[data-v144-template-search]');if(search){const id=search.dataset.v144TemplateSearch;adjustState.v144LibraryUi[id].query=search.value;refreshLibrary(id);return;}const map=[['v144Scale','scalePct','%'],['v144Move','movePct','%'],['v144Angle','angleDeg','°'],['v144Effect','effectPct','%']];for(const [dk,key,unit] of map){const attr='data-'+dk.replace(/[A-Z]/g,m=>'-'+m.toLowerCase()),el=e.target.closest(`[${attr}]`);if(el){const id=el.dataset[dk];params(id)[key]=Number(el.value);if(el.nextElementSibling)el.nextElementSibling.textContent=el.value+unit;syncPrompt(id);return;}}const custom=e.target.closest('[data-v142-custom-subject]');if(custom){syncPrompt(custom.dataset.v142CustomSubject);return;}},true);
  document.addEventListener('change',e=>{if(curView!=='adjust')return;const filter=e.target.closest('[data-v144-template-filter]');if(filter){const id=filter.dataset.v144TemplateFilter;adjustState.v144LibraryUi[id].filter=filter.value;refreshLibrary(id);return;}const p=e.target.closest('[data-v144-scale],[data-v144-move],[data-v144-angle],[data-v144-effect]');if(p){adjustPushHistory('更新 V14.4 组合参数');renderAdjustView();return;}const subject=e.target.closest('[data-v142-subject-type]');if(subject){const id=subject.dataset.v142SubjectType;setTimeout(()=>{adjustState.v144RecommendationSets[id]=null;ensure144();syncPrompt(id,'切换主体类型并刷新模板组合');renderAdjustView();},0);}},true);
  document.addEventListener('toggle',e=>{const d=e.target.closest&&e.target.closest('[data-v144-more]');if(!d)return;adjustState.v144MoreOpen=adjustState.v144MoreOpen||{};adjustState.v144MoreOpen[d.dataset.v144More]=!!d.open;},true);
  document.addEventListener('dragstart',e=>{const chip=e.target.closest('[data-v144-sort-item]');if(!chip)return;dragState={id:chip.dataset.brushId,tid:chip.dataset.v144SortItem};chip.classList.add('dragging');if(e.dataTransfer){e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragState.tid);}},true);
  document.addEventListener('dragover',e=>{const chip=e.target.closest('[data-v144-sort-item]');if(!chip||!dragState||chip.dataset.brushId!==dragState.id)return;e.preventDefault();document.querySelectorAll('.v144-order-chip.drag-over').forEach(x=>x.classList.remove('drag-over'));chip.classList.add('drag-over');if(e.dataTransfer)e.dataTransfer.dropEffect='move';},true);
  document.addEventListener('drop',e=>{const chip=e.target.closest('[data-v144-sort-item]');if(!chip||!dragState||chip.dataset.brushId!==dragState.id)return;e.preventDefault();const r=chip.getBoundingClientRect(),after=e.clientY>r.top+r.height/2;reorder(dragState.id,dragState.tid,chip.dataset.v144SortItem,after);dragState=null;},true);
  document.addEventListener('dragend',()=>{document.querySelectorAll('.v144-order-chip.dragging,.v144-order-chip.drag-over').forEach(x=>x.classList.remove('dragging','drag-over'));dragState=null;},true);
  requestAnimationFrame(()=>{ensure144();if(curView==='adjust')renderAdjustView();});
})();
